"""empty message

Revision ID: 6b1bc560a12b
Revises: 598e25fcb9bf
Create Date: 2023-08-16 11:16:38.897423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1bc560a12b'
down_revision = '598e25fcb9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'testsons', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testsons', type_='unique')
    # ### end Alembic commands ###
