"""empty message

Revision ID: a093d317ede9
Revises: 6b1bc560a12b
Create Date: 2023-08-16 11:30:09.104832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a093d317ede9'
down_revision = '6b1bc560a12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testsons', sa.Column('audio', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testsons', 'audio')
    # ### end Alembic commands ###
